# Generated by Django 2.2.16 on 2022-10-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_conf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_conf",
            new_name="email_confirmed",
        ),
    ]
