# Generated by Django 2.2.16 on 2022-10-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20221013_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_confirmed",
        ),
    ]
