# Generated by Django 2.2.16 on 2022-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20221005_0845"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="First name"
            ),
        ),
    ]
