# Generated by Django 2.2.16 on 2022-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20221005_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="First name"
            ),
        ),
    ]
