# Generated by Django 2.2.16 on 2022-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20221005_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="First name"
            ),
        ),
    ]
