# Generated by Django 2.2.16 on 2022-10-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20221006_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("User", "User"),
                    ("Moderator", "Moderator"),
                    ("Admin", "Admin"),
                ],
                default="User",
                max_length=1,
                verbose_name="Role",
            ),
        ),
    ]
