# Generated by Django 2.2.16 on 2022-10-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите категорию",
                        max_length=256,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Укажите URL категории",
                        unique=True,
                        verbose_name="URL категории",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "slug"),
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст комментария",
                        verbose_name="Текст комментария",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата комментария"
                    ),
                ),
            ],
            options={
                "ordering": ["pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите жанр",
                        max_length=256,
                        verbose_name="Жанр",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Укажите URL жанра",
                        unique=True,
                        verbose_name="URL жанра",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "slug"),
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите текст отзыва",
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        help_text="Оцените произведение от 1 до 10",
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отзыва"
                    ),
                ),
            ],
            options={
                "ordering": ["pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=256,
                        verbose_name="Название",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Укажите год выпуска",
                        verbose_name="Год выпуска",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Укажите описание (необязательно к заполнению)",
                        max_length=256,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="title",
                        to="reviews.Categories",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Выберите жанр",
                        related_name="title",
                        to="reviews.Genres",
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
