# Generated by Django 2.2.16 on 2022-10-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221009_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name', 'slug')},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ('name', 'slug')},
        ),
    ]
